Fix MRO errors with `BaseEstimator`
scikit-learn requires that `BaseEstimator` comes after the `*Mixin`
classes in the class definitions.
With the new 1.6.0 version, classes that do not comply with this start
raising the following error:

```
'super' object has no attribute '__sklearn_tags__'.
```